version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.58.1
    steps:
      - checkout
      - run:
          name: Show kernel version
          command: uname -a

workflows:
  say-hello-workflow:
    jobs:
      - test
