name: CI
on: [push, pull_request]

# Note: runnner must use BTF(BPF Typed format) Kernel
# Ubuntu >= 20.10
jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install libraries
        run: sudo apt-get install -y libelf-dev libgcc-s1 libbpf-dev clang linux-tools-common linux-tools-generic make pkg-config
      - run: rustup component add rustfmt clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo libbpf
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: libbpf-cargo
      - name: Generate vmlinux.h
        run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > ./sprofiler-bpf/src/bpf/vmlinux.h
      - name: cargo libbpf make
        uses: actions-rs/cargo@v1
        with:
          command: libbpf
          args: make
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install libraries
        run: sudo apt-get install -y libelf-dev libgcc-s1 libbpf-dev clang linux-tools-common linux-tools-generic make pkg-config
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo libbpf
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: libbpf-cargo
      - name: Generate vmlinux.h
        run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > ./sprofiler-bpf/src/bpf/vmlinux.h
      - name: cargo libbpf make
        uses: actions-rs/cargo@v1
        with:
          command: libbpf
          args: make
      - name: cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
