name: "pre-release"

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          components: rustfmt, clippy
      - name: Install libraries
        run: sudo apt-get install -y libelf-dev libgcc-s1 libbpf-dev clang linux-tools-common linux-tools-generic make pkg-config
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo libbpf
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: libbpf-cargo cargo-deb
      - name: Generate vmlinux.h
        run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > ./sprofiler/src/bpf/vmlinux.h
      - name: cargo libbpf make
        uses: actions-rs/cargo@v1
        with:
          command: libbpf
          args: make
      - name: Create debian package
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: -p sprofiler
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            ./target/debian/*.deb
