name: Unit Tests
on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install libraries
        run: sudo apt-get install -y libelf-dev libgcc-s1 libbpf-dev clang linux-tools-common make pkg-config
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo libbpf
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: libbpf-cargo
      - name: Temporary build to generate vmlinux.h
        run: cargo build --all-features || true
      - name: cargo libbpf make
        uses: actions-rs/cargo@v1
        with:
          command: libbpf
          args: make
      - name: cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
